---
name: IntelliJ Code Format
description: |
  Runs the IntelliJ formatter to apply the IDE style rules.
inputs:
  path:
    description: |
      Path to project directory. The formatter is executed recursively from here. Must be relative to the workspace.
    required: false
    default: '.'
  include-pattern:
    description: |
      Pattern for files to include. Supports glob-style wildcards. Multiple patterns can be separated by commas.
    required: false
    default: '*'
  style-settings-file:
    description: A path to IntelliJ IDEA code style settings .xml file.
    required: false
    default: 'unset'
outputs:
  files-changed:
    description: Zero if none changed, greater if at least one file changed.
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
    - ${{ inputs.include-pattern }}
    - ${{ inputs.style-settings-file }}
