name: IntelliJ Test Format

on:
  pull_request:
    paths:
      - '*'
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Cache IDEA
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/_github_workflow/idea-cache
          key: ${{ runner.os }}-idea-cache-v2
      - name: Run Formatter
        uses: ./
        with:
          include-glob: "*.java"
          path: test/
          style-settings-file: "./custom_intellij_format"

